### ISSUE TITLE
Handle Annotations

### ISSUE THREAD

**Issue by ataraxie** [ataraxie/codeshovel#1]
Java Annotations are currently ignored. But they can be an essential part of methods. We should look into how we could deal with them.

**Comment by rtholmes** [comment]
A related dupe was added by @braxtonhall with some good examples:
https://github.com/ataraxie/codeshovel/issues/19#issue-492359839

**Comment by rtholmes** [comment]
Closed inadvertently.

**Comment by rtholmes** [comment]
@ishtiaque05 this can be yours!

**Comment by ishtiaque05** [comment]
`CodeShovel` now is able to capture method annotations :tada:.  It also captures the annotation at every change commit of a method. 
Consider a simple example:
```java
@Test
@SuppressWarnings("deprecated")
public void foo() {}
```
The `json` result will contain a key name `functionAnnotation` that contains the value as string: `Test, SuppressWarnings`

**Comment by ataraxie** [comment]
Very nice @ishtiaque05 !!

**Comment by rtholmes** [comment]
This is great @ishtiaque05 ! I'll cleanup the icse branch as part of the release for the CRC and then we'll get this as the start of the research branch from there!

**Comment by braxtonhall** [comment]
Yay! When this is merged it should only be a couple lines to get it working with Python as well :)

**Comment by braxtonhall** [comment]
OK so status is that Annotations are captured, but changes are still not reported to the user. Let's get that done eventually :)

**Comment by ishtiaque05** [comment]
Currently `CodeShovel` keeps track of body changes, signature changes, and cross-file changes. For annotation change what does it falls under? I think it might be part of the signature change. What does everyone think? Also, another sub changes for annotation could be `annotation params change`.

**Comment by braxtonhall** [comment]
I like the `MetaInfoChange` because I think that would best capture `ContextChange` in #2

**Comment by ishtiaque05** [comment]
We had a discussion and we are going to track `AnnotationChange` as a part of `SignatureChange`. We will also introduce `ContextChange` to track `ParentChanges`

**Comment by braxtonhall** [comment]
I think the last TODO for this issue would be to ensure that the annotation is captured in the diff.
I think the diffs may start at the signature

**Comment by ishtiaque05** [comment]
> I think the last TODO for this issue would be to ensure that the annotation is captured in the diff.
> I think the diffs may start at the signature

Pasting an example of output here just for reference

```json
"5cb4bb94d6638dc9a8d6c58f7c8faa6af5b327d0": {
      "type": "Yannotationchange",
      "commitMessage": "Custom annotation\n",
      "commitDate": "16/02/21 11:17 PM",
      "commitName": "5cb4bb94d6638dc9a8d6c58f7c8faa6af5b327d0",
      "commitAuthor": "Syed Ishtiaque Ahmad",
      "commitDateOld": "09/02/21 1:15 PM",
      "commitNameOld": "cd673ea9d766325aab7fc5917525f143073a2e0b",
      "commitAuthorOld": "Syed Ishtiaque Ahmad",
      "daysBetweenCommits": 7.42,
      "commitsBetweenForRepo": 2,
      "commitsBetweenForFile": 1,
      "actualSource": "\tpublic void testSumagain()  throws ArithmeticException, ArrayIndexOutOfBoundsExceptionthrows {\n\t\t// Given\n\t\t// testing annotations\n\t\tCalculator calculator \u003d new Calculator();\n\t\t// When\n\t\tint result \u003d calculator.sum(2, 2);\n\t\tint iby4 \u003d calculator.incrementBy4(result);\n\t\t// Then\n\t\tAssert.assertTrue(result \u003d\u003d 4);\n\t\tAssert.assertEquals(8, iby4);\n\t}",
      "path": "src/test/java/com/github/stokito/unitTestExample/calculator/CalculatorTest.java",
      "functionStartLine": 13,
      "functionName": "testSumagain",
      "functionAnnotation": "@Test,@Override,@MyCustomAnnotation(testName \u003d \"testSumAgain\", startline \u003d \"13\")",
      "diff": "",
      "extendedDetails": {
        "oldValue": "@Test,@Override",
        "newValue": "@Test,@Override,@MyCustomAnnotation(testName \u003d \"testSumAgain\", startline \u003d \"13\")"
      }
    }
```
