### ISSUE TITLE
Method rename detection

### ISSUE THREAD

**Issue by nickbradley** [ataraxie/codeshovel#12]
In some cases CodeShovel reports that a method was renamed but the original method still exists. In these cases, I would expect that CodeShovel would report as introduced.

77cfe/junit-platform-launcher/src/main/java/org/junit/platform/launcher/core/DefaultLauncher.java/discoverRoot___discoveryRequest-LauncherDiscoveryRequest__phase-String.json

commit: 830b6d5976b6db01dad3866cfb3d54c6216b1252: "Ymultichange(Yrename,Yreturntypechange,Ymodifierchange,Ybodychange)",

**Comment by rtholmes** [comment]
I think this has been resolved by the icse2021 CRC work.
