### ISSUE TITLE
Improve and test JavaScript parser

### ISSUE THREAD

**Issue by ataraxie** [ataraxie/codeshovel#15]
A JavaScript parser for CodeShovel has already implemented using the JDK's `Nashorn` engine. But it is still very rudimentary and needs to be improved and tested with more stubs. A few stubs have been created for the jQuery repo but the latest status has not been checked and most stub don't include an `expectedResult`.

Note: after quite some research I could not find a JavaScript AST parser that supports ES6 well enough, so right now I think we'll have to stick to ES5 repos only.

**Comment by rtholmes** [comment]
Closing for now. Javascript has moved away from Nashorn, @braxtonhall can probably do this better with his antlr-based implementation he has working for TypeScript.
