### ISSUE TITLE
Additional Steps for Setting up Development Environment for CodeShovel

### ISSUE THREAD

**Issue by jyoo980** [ataraxie/codeshovel#16]
Hey Felix

I thought it might be a good idea to have this written down in the repo as a record of some additional steps to take in setting up the development environment for CodeShovel. I wasn't able to find these steps in the readme, so I don't think we're duplicating efforts here.

**Setting up src, test, resource modules**
The following should be configured in your IDE below as follows
* **Source folders:** `src/main/java`
* **Test source folders:** `src/test/java`
* **Resource folders:** `src/main/resources`
* **Test resource folders:** `src/test/resources`
* **Excluded folders:** `target`

**Resolving issues with external dependencies**
Make sure you have the Maven plugin installed for IntelliJ. Once you have it installed, it will prompt you to set the `pom.xml` file and recognize CodeShovel as a maven project.

Following these steps removed all the "red" from the initially cloned version of the repo. Let me know if you think I missed any steps!

I'd be happy to branch and make a PR with these changes to the README if you think that'd be a good idea!

**Comment by jyoo980** [comment]
@ataraxie How does this look?

**Comment by ataraxie** [comment]
Oops, I'm really sorry James, I missed this somehow. Yes, it's a great idea that you create a PR for the readme!

I'm wondering why you had to set up these settings manually. Probably they aren't the default if you don't have the Maven addon installed from the beginning.

Will you be still around next year?

**Comment by jyoo980** [comment]
Yep, I’ll be around next year for sure!

I’ll go ahead and make a PR today, happy holidays!

James
