### ISSUE TITLE
Missing information in the readme file

### ISSUE THREAD

**Issue by shaifulcse** [ataraxie/codeshovel#26]
When building the JAR file and running from the command line, it does not say that we need to checkout the downloaded project (e.g., checkout) to the appropriate commit. Consider the example provided: it will not work for the current checkstyle state. We need to checkout to "119fd4fb33bef9f5c66fc950396669af842c21a3".

I AM WRITING ALL OF THESE SO WHEN WE MAKE SOMETHING FOR THE ARTIFACT TRACK, WE CAN MAKE CORRECTIONS.

**Comment by rtholmes** [comment]
Fixed ind the docs.
