### ISSUE TITLE
OutOfMemoryError when running with multiple repositories

### ISSUE THREAD

**Issue by ataraxie** [ataraxie/codeshovel#37]
This has been a forever ongoing problem: there is some kind of memory leak which produces an error after a few repositories. The problem is that some references are not garbage-collected after running each configuration. So data will just pile up with each new configuration and at some point will lead to an error.

I have tried quite hard in early 2019 to fix this and was not successful. When we ran all tests for our empirical analysis, we used the Docker image which ran `DockerExecution.java` for each of the configurations. This was equal to invoking CodeShovel separately for each configuration (i.e. like having a loop in a shell script executing CodeShovel for each config).

**Comment by ataraxie** [comment]
A workaround for this problem is to just set the Java heap space to a very high value. I can run all tests with a heap space of 12GB. This may swap some memory but it's still working fine. I ran all tests with the following configuration:

Environment variables: `REPO_DIR=/Users/fgrund/dev/codeshovel-repos;LANG=java`
Java arguments: `-ea -Xmx12G`

![image](https://user-images.githubusercontent.com/1646086/104131653-96498880-532c-11eb-822d-c118c0c8e380.png)

**Comment by rtholmes** [comment]
@ataraxie if you want to confirm this we can close this issue!

**Comment by ataraxie** [comment]
@rtholmes Looks good to me! I see some potential improvements but I'm totally ok with closing this for now if it works!

**Comment by rtholmes** [comment]
I reworked this some more and it is definitely fixed. Have run the whole suite 100+ times with `-Xmx4g`.
