### ISSUE TITLE
IntelliJ only showing test results after running ALL the tests

### ISSUE THREAD

**Issue by ataraxie** [ataraxie/codeshovel#39]
It used to be that IntelliJ showed the results for each test while the dynamic tests were executing. Now, it's only showing the results after running ALL the tests:
![image](https://user-images.githubusercontent.com/1646086/104111232-6c448780-5294-11eb-86e4-39face6b485e.png)

This is very annoying and we should look if there's a way to fix this.

**Comment by rtholmes** [comment]
This might be related:

https://github.com/gradle/gradle/issues/5975

**Comment by rtholmes** [comment]
Fixed in fd0f926.
