### ISSUE TITLE
Env Z_elasticsearch-RestRequest-method has incorrect expected result

### ISSUE THREAD

**Issue by ataraxie** [ataraxie/codeshovel#41]
The expected result of this env is not correct:
```
"fcf1e41e429b10e03c5cf9b8551636df7519b4c5": "Ymultichange(Ymovefromfile,Ybodychange)",
"99f88f15c5febbca2d13b5b5fda27b844153bf1a": "Yfilerename",
"2d1b0587dd57a74c48022f5456467ab8873a2d0c": "Ymultichange(Ymovefromfile,Yreturntypechange,Yrename,Yparameterchange)",
"117bc68af3987004ade7e56f0aebace72cd1d0ef": "Yintroduced"
```

An older version of CodeShovel started tracing a test method with `fcf1e41e`. There must have been a mistake while creating the expected result for the validation phase. The commit `fcf1e41e` is very tricky. The most simple "correct" result would be a `Yintroduced` in this commit.

**Comment by rtholmes** [comment]
This has been updated by Shaiful in my current ICSE branch.
