### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rtholmes** [ataraxie/codeshovel#45]
We need a license for this to be submitted to the ICSE artifact track. Also: we should have a license.

**Comment by ataraxie** [comment]
Oh. I have no knowledge about this really. The only license I ever created is this one:
https://github.com/scandio/e4-framework/blob/master/LICENSE

How do you want to handle this? I think you know much more about this than I. Also by the way, I'd be ok with moving the repo to somewhere else if you prefer that!

**Comment by rtholmes** [comment]
If I had to choose I'd go with either
MIT https://choosealicense.com/licenses/mit/
CC-by-SA https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by rtholmes** [comment]
@ataraxie actually the MIT license is so short maybe it's just the best way to go :)
