### ISSUE TITLE
ICSE 2021 Camera Ready Preparation

### ISSUE THREAD

**Issue by rtholmes** [ataraxie/codeshovel#47]
**The [origin/icse2021](https://github.com/ataraxie/codeshovel/tree/icse2021) branch represents CodeShovel as it existed when the ICSE 2021 paper was published.**

I've pulled `origin/master`, `origin/research`, `origin/develop`, and `origin/shaifuls-changes` into `origin/icse2021` in preparation for final ICSE validation. 

To finalize the paper we need to (in the `origin/icse2021` branch):

- [x] Add the FinerGit / IntelliJ / git log data files (@shaifulcse).
- [x] Upload the oracle files to repo (@shaifulcse).
- [x] Add description of how to use / what the oracle & finergit files above mean to the README (@shaifulcse)
- [x] Finalize latex for the ICSE submission (@shaifulcse)

- [x] Look at the one flink oracle file that is incomplete (@rtholmes).
- [x] Refactor `stubs` to `oracles` consistently through the repo (@rtholmes).
- [x] Confirm FinerGit runtime performance with observations from the initial submission (@rtholmes).
- [x] Improve the conceptual flow of the matching code. (@rtholmes on a separate branch to not block other work)
- [x] Confirm the implementation passes the oracle to the same degree described in the paper. (@rtholmes)
- [x] Confirm the constants match the description in the paper. (@rtholmes)

At that point we should be done (for ICSE 2021).

**Comment by rtholmes** [comment]
380ccf5f4126c22a12bcb0b32539df66d169c1b2 & fd0f92697a57bfc4c9157b80f75aadb18a235f04 fix the memory leak issue (#37) and the test running issue (#39).

**Comment by ataraxie** [comment]
Great work in those two commits @rtholmes !! I think putting the code into the test suite in fd0f926 is not the "final solution" but if it works this way that's fine for now!

**Comment by rtholmes** [comment]
> Great work in those two commits @rtholmes !! I think putting the code into the test suite in [fd0f926](https://github.com/ataraxie/codeshovel/commit/fd0f92697a57bfc4c9157b80f75aadb18a235f04) is not the "final solution" but if it works this way that's fine for now!

Don't worry, I redid this again in 730b508 which I hope addresses your concerns! The test part is only ~4 lines of code now.

**Comment by rtholmes** [comment]
`reid_icse2021` merged into `icse2021` and deleted. `master` is now up-to-date with `icse2021`.
