### ISSUE TITLE
NestedMethod strange behaviour

### ISSUE THREAD

**Issue by braxtonhall** [ataraxie/codeshovel#52]
I'm not sure I completely understand the rationale for the new behaviour regarding function IDs starting at https://github.com/ataraxie/codeshovel/commit/f14be5c97a99fdbc4937e35653bad8baa6c99d53

Given the class
```java
class A {
    class B {
        void method() {}
        class C {
            void method() {}
        }
    }
}
```
Before this commit, we received methods with two different IDs:
`B#method` and `C#method`.

After the commit in question, we get `$method` and `$method`

What was the reason for this change?

**Comment by rtholmes** [comment]
This must have been for nested (and anonymous?) class support @ataraxie ?

**Comment by ataraxie** [comment]
Yes, I think so. And I think I had already fixed this on master.

**Comment by ataraxie** [comment]
Oh now I got the question, my previous comment doesn't make any sense, sorry.

So there were some cases even among the Oracle methods where these methods couldn't be traced with the previous type of ID matching. I could make these methods work by simply matching for `$method` for nested classes. I've never really seen triple nested methods in Java, so I'm not sure whether this is something that should be considered.

You can really free to change this if you think you want this be implemented in a better way.

**Comment by braxtonhall** [comment]
I think for Python, JavaScript and TypeScript it makes more sense to use the old way, but perhaps this new way will be better for Java. I think i n the #54 pull I'll restore the old code in the AbstractFunction superclass, and let it be overridden by the JavaFunction.

**Comment by rtholmes** [comment]
That seems fine to me @braxtonhall; if you get a chance could you push that through? No rush at all.
