### ISSUE TITLE
Is it possible to check the change history of each method's line?

### ISSUE THREAD

**Issue by onewhl** [ataraxie/codeshovel#72]
Hi,

I'm curious if it is possible to check the history of each method's line using CodeShovel (`git blame` doest something like that if I'm not mistaken).
For example, provide a list of the commits (including author, date, and diff) the line was changed in.

Thanks,
Zarina

**Comment by rtholmes** [comment]
Unfortunately, CodeShovel doesn't differentiate between lines within a method, so it is not possible with our approach. But you could use CodeShovel to learn about all of the commits to a method (which would give you author, date, an diff) and then as a post-processing step just look at the provenance of your line-of-interest.

**Comment by onewhl** [comment]
I get it, thank you for responding!
